from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


def require(path: str, needle: str, label: str) -> None:
    text = read(path)
    if needle not in text:
        raise AssertionError(f"missing {label} in {path}: {needle}")


def forbid(path: str, needle: str, label: str) -> None:
    text = read(path)
    if needle in text:
        raise AssertionError(f"unexpected {label} in {path}: {needle}")


def require_file(path: str, label: str) -> None:
    if not (ROOT / path).exists():
        raise AssertionError(f"missing {label}: {path}")


def forbid_file(path: str, label: str) -> None:
    if (ROOT / path).exists():
        raise AssertionError(f"unexpected {label}: {path}")


def main() -> None:
    require("frontend/package.json", '"react"', "React dependency")
    require("frontend/package.json", '"vite"', "Vite dependency")
    require("frontend/vite.config.js", 'root: "react"', "React app root")
    require("frontend/vite.config.js", 'outDir: "../dist"', "Vite build output")
    require("frontend/react/src/main.jsx", "createRoot", "React mount")
    require_file("frontend/react/src/api/client.js", "React API client")
    require("frontend/react/src/api/client.js", "export async function apiRequest", "apiRequest helper")
    require("frontend/react/src/api/client.js", "credentials: \"include\"", "cookie credentials")
    require("frontend/react/src/api/client.js", "throw new ApiError", "structured API errors")
    require_file("frontend/react/src/auth/AuthProvider.jsx", "AuthProvider scaffold")
    require_file("frontend/react/src/data/navigation.js", "React navigation data module")
    require("frontend/react/src/data/navigation.js", "export const sidebarTools", "sidebar tool config")
    forbid("frontend/react/src/data/navigation.js", "manualToolOptions", "redundant manual tool config")
    forbid("frontend/react/src/data/navigation.js", "promptSuggestions", "redundant prompt suggestion config")
    require("frontend/react/src/auth/AuthProvider.jsx", "createContext", "auth context")
    require("frontend/react/src/auth/AuthProvider.jsx", "export function AuthProvider", "AuthProvider export")
    require("frontend/react/src/auth/AuthProvider.jsx", "export function useAuth", "useAuth export")
    require("frontend/react/src/auth/AuthProvider.jsx", "getCurrentUser", "current user loader")
    require("frontend/react/src/auth/AuthProvider.jsx", "login", "auth login action")
    require("frontend/react/src/auth/AuthProvider.jsx", "register", "auth register action")
    require("frontend/react/src/auth/AuthProvider.jsx", "logout", "auth logout action")
    require("frontend/react/src/auth/AuthProvider.jsx", "applyAuthState", "auth provider receives auth state")
    require("frontend/react/src/auth/AuthProvider.jsx", "knowflow:react-auth-state-updated", "auth provider listens for React auth state")
    require("frontend/react/src/main.jsx", "AuthProvider", "AuthProvider mounted")
    require("frontend/react/src/App.jsx", "WorkbenchShell", "React shell component")

    app_source = read("frontend/react/src/App.jsx")
    if "dangerouslySetInnerHTML" in app_source:
        raise AssertionError("React shell should not use dangerouslySetInnerHTML")
    if "legacyTemplate" in app_source:
        raise AssertionError("React shell should not import legacyTemplate")

    for component_name in ["AuthScreen", "Sidebar", "ChatPage", "KnowledgePage", "SettingsPage", "Toast"]:
        require("frontend/react/src/App.jsx", f"import {{ {component_name} }}", f"{component_name} import")
        require_file(f"frontend/react/src/components/{component_name}.jsx", f"{component_name} component file")
        require(f"frontend/react/src/components/{component_name}.jsx", f"export function {component_name}", f"{component_name} named export")
        forbid("frontend/react/src/App.jsx", f"function {component_name}", f"inline {component_name} component")

    require("frontend/react/src/components/Toast.jsx", "useState", "React toast owns message state")
    require("frontend/react/src/components/Toast.jsx", "visible", "React toast owns visibility state")
    require("frontend/react/src/components/Toast.jsx", "knowflow:react-toast", "React toast receives React toast data")
    require("frontend/react/src/components/Toast.jsx", "toastTimerRef", "React toast owns hide timer")

    require_file("frontend/react/src/components/ChatComposerForm.jsx", "ChatComposerForm component file")
    require("frontend/react/src/components/ChatComposerForm.jsx", "export function ChatComposerForm", "ChatComposerForm named export")
    require_file("frontend/react/src/components/ChatContextToolbar.jsx", "ChatContextToolbar component file")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "export function ChatContextToolbar", "ChatContextToolbar named export")
    require_file("frontend/react/src/components/ChatTopbar.jsx", "ChatTopbar component file")
    require("frontend/react/src/components/ChatTopbar.jsx", "export function ChatTopbar", "ChatTopbar named export")
    require_file("frontend/react/src/components/ChatMessages.jsx", "ChatMessages component file")
    require("frontend/react/src/components/ChatMessages.jsx", "export function ChatMessages", "ChatMessages named export")
    require_file("frontend/react/src/components/ChatEvidenceDrawer.jsx", "ChatEvidenceDrawer component file")
    require("frontend/react/src/components/ChatEvidenceDrawer.jsx", "export function ChatEvidenceDrawer", "ChatEvidenceDrawer named export")
    require_file("frontend/react/src/components/KnowledgeHeader.jsx", "KnowledgeHeader component file")
    require("frontend/react/src/components/KnowledgeHeader.jsx", "export function KnowledgeHeader", "KnowledgeHeader named export")
    require_file("frontend/react/src/components/KnowledgeSummary.jsx", "KnowledgeSummary component file")
    require("frontend/react/src/components/KnowledgeSummary.jsx", "export function KnowledgeSummary", "KnowledgeSummary named export")
    require_file("frontend/react/src/components/KnowledgeRail.jsx", "KnowledgeRail component file")
    require("frontend/react/src/components/KnowledgeRail.jsx", "export function KnowledgeRail", "KnowledgeRail named export")
    require_file("frontend/react/src/components/KnowledgeDocuments.jsx", "KnowledgeDocuments component file")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "export function KnowledgeDocuments", "KnowledgeDocuments named export")
    require_file("frontend/react/src/components/KnowledgeModals.jsx", "KnowledgeModals component file")
    require("frontend/react/src/components/KnowledgeModals.jsx", "export function KnowledgeModals", "KnowledgeModals named export")
    require_file("frontend/react/src/components/KnowledgeRetrievalDrawer.jsx", "KnowledgeRetrievalDrawer component file")
    require("frontend/react/src/components/KnowledgeRetrievalDrawer.jsx", "export function KnowledgeRetrievalDrawer", "KnowledgeRetrievalDrawer named export")
    require_file("frontend/react/src/components/SettingsHeader.jsx", "SettingsHeader component file")
    require("frontend/react/src/components/SettingsHeader.jsx", "export function SettingsHeader", "SettingsHeader named export")
    require_file("frontend/react/src/components/ModelConfigForm.jsx", "ModelConfigForm component file")
    require("frontend/react/src/components/ModelConfigForm.jsx", "export function ModelConfigForm", "ModelConfigForm named export")
    require_file("frontend/react/src/components/ModelProviderSelector.jsx", "ModelProviderSelector component file")
    require("frontend/react/src/components/ModelProviderSelector.jsx", "export function ModelProviderSelector", "ModelProviderSelector named export")
    require_file("frontend/react/src/components/ModelListPanel.jsx", "ModelListPanel component file")
    require("frontend/react/src/components/ModelListPanel.jsx", "export function ModelListPanel", "ModelListPanel named export")
    require_file("frontend/react/src/components/SettingsSidePanel.jsx", "SettingsSidePanel component file")
    require("frontend/react/src/components/SettingsSidePanel.jsx", "export function SettingsSidePanel", "SettingsSidePanel named export")
    require_file("frontend/react/src/data/settings.js", "settings data module")
    require("frontend/react/src/data/settings.js", "export const providerCards", "provider card config")

    require("frontend/react/src/components/AuthScreen.jsx", "auth-screen", "React auth screen markup")
    require("frontend/react/src/components/AuthScreen.jsx", "useAuth", "auth screen consumes auth provider state")
    require("frontend/react/src/components/AuthScreen.jsx", "authenticated", "auth screen uses authenticated state")
    require("frontend/react/src/components/AuthScreen.jsx", "loading", "auth screen uses loading state")
    require("frontend/react/src/components/AuthScreen.jsx", "authScreenClassName", "auth screen dynamic visibility class")
    require("frontend/react/src/components/AuthScreen.jsx", "document.body.classList.toggle", "auth screen body lock sync")
    require("frontend/react/src/components/AuthScreen.jsx", "useState", "auth screen owns mode state")
    require("frontend/react/src/components/AuthScreen.jsx", "setMode", "auth mode setter")
    require("frontend/react/src/components/AuthScreen.jsx", "handleLogin", "React login submit handler")
    require("frontend/react/src/components/AuthScreen.jsx", "handleRegister", "React register submit handler")
    require("frontend/react/src/components/AuthScreen.jsx", "onSubmit={handleLogin}", "login form wired to React submit")
    require("frontend/react/src/components/AuthScreen.jsx", "onSubmit={handleRegister}", "register form wired to React submit")
    require("frontend/react/src/components/AuthScreen.jsx", "knowflow:react-auth-success", "React auth success event")
    require("frontend/react/src/components/AuthScreen.jsx", "knowflow:react-toast", "React auth toast event")
    require("frontend/react/src/components/AuthScreen.jsx", "oauthProviders", "OAuth provider state")
    require("frontend/react/src/components/Sidebar.jsx", "function UserMenu", "isolated user menu component")
    require("frontend/react/src/components/Sidebar.jsx", "function SessionHistory", "isolated session history component")
    require("frontend/react/src/components/Sidebar.jsx", "knowflow:react-sessions-refresh-request", "React session list receives refresh requests")
    require("frontend/react/src/components/Sidebar.jsx", "sessionApi", "React session list owns session API calls")
    require("frontend/react/src/components/Sidebar.jsx", "loadSessions", "React session list refresh handler")
    require("frontend/react/src/components/Sidebar.jsx", "groupSessions", "React session list groups sessions")
    require("frontend/react/src/components/Sidebar.jsx", "filteredSessions", "React session list filters sessions")
    require("frontend/react/src/components/Sidebar.jsx", "openMenuSessionId", "React session menu state")
    require("frontend/react/src/components/Sidebar.jsx", "knowflow:react-session-continue", "React session continue event")
    require("frontend/react/src/components/Sidebar.jsx", "handleSessionRename", "React session rename handler")
    require("frontend/react/src/components/Sidebar.jsx", "handleSessionDelete", "React session delete handler")
    require("frontend/react/src/components/Sidebar.jsx", "sessionApi.update", "React session rename API call")
    require("frontend/react/src/components/Sidebar.jsx", "sessionApi.delete", "React session delete API call")
    require("frontend/react/src/components/Sidebar.jsx", "useAuth", "user menu consumes auth provider state")
    require("frontend/react/src/components/Sidebar.jsx", "menuOpen", "React user menu owns open state")
    require("frontend/react/src/components/Sidebar.jsx", "handleUserMenuToggle", "React user menu toggle handler")
    require("frontend/react/src/components/Sidebar.jsx", "handleLogout", "React logout handler")
    require("frontend/react/src/components/Sidebar.jsx", "knowflow:react-auth-logout", "React logout event")
    require("frontend/react/src/components/Sidebar.jsx", "avatarUrl", "user menu renders avatar from auth state")
    require("frontend/react/src/components/Sidebar.jsx", "handlePageChange", "React sidebar page handler")
    require("frontend/react/src/components/Sidebar.jsx", "knowflow:react-page-change", "React page navigation event")
    require("frontend/react/src/components/Sidebar.jsx", "handleNewChat", "React new chat handler")
    require("frontend/react/src/components/Sidebar.jsx", "knowflow:react-new-chat", "React new chat event")
    require("frontend/react/src/components/Sidebar.jsx", "handleSidebarToggle", "React sidebar toggle handler")
    require("frontend/react/src/components/Sidebar.jsx", "knowflow:react-sidebar-toggle", "React sidebar toggle event")
    require("frontend/react/src/components/Sidebar.jsx", "handleSessionSearch", "React session search handler")
    require("frontend/react/src/components/Sidebar.jsx", "sidebarTools.map", "sidebar renders configured tools")
    require("frontend/react/src/components/Sidebar.jsx", "function RuntimeStatus", "React runtime status component")
    require("frontend/react/src/components/Sidebar.jsx", "runtimeApi.get", "React runtime status loads API data")
    require("frontend/react/src/components/Sidebar.jsx", "knowflow:react-refresh", "React runtime status refreshes with app refresh")
    require("frontend/react/src/components/ChatPage.jsx", "ChatTopbar", "chat page renders topbar component")
    require("frontend/react/src/components/ChatPage.jsx", "ChatMessages", "chat page renders messages component")
    require("frontend/react/src/components/ChatPage.jsx", "ChatContextToolbar", "chat page renders context toolbar component")
    require("frontend/react/src/components/ChatPage.jsx", "ChatComposerForm", "chat page renders composer form component")
    require("frontend/react/src/components/ChatPage.jsx", "ChatEvidenceDrawer", "chat page renders evidence drawer component")
    forbid("frontend/react/src/components/ChatComposerForm.jsx", "ChatToolControls", "redundant manual tool controls")
    forbid("frontend/react/src/components/ChatPage.jsx", "import { ChatComposer }", "redundant prompt shelf import")
    forbid("frontend/react/src/components/ChatPage.jsx", "<ChatComposer />", "redundant prompt shelf component")
    require("frontend/react/src/components/ChatComposerForm.jsx", "chat-form", "composer form id retained")
    require("frontend/react/src/components/ChatComposerForm.jsx", "composer-plus-btn", "composer plus id retained")
    require("frontend/react/src/components/ChatComposerForm.jsx", "composer-menu", "composer menu id retained")
    require("frontend/react/src/components/ChatComposerForm.jsx", "chat-file-input", "chat file input id retained")
    require("frontend/react/src/components/ChatComposerForm.jsx", "composer-kb-select", "composer kb select id retained")
    require("frontend/react/src/components/ChatComposerForm.jsx", "chat-submit-btn", "chat submit id retained")
    require("frontend/react/src/components/ChatComposerForm.jsx", "attachments", "React attachment tray owns attachment state")
    require("frontend/react/src/components/ChatComposerForm.jsx", "knowflow:react-attachments-updated", "React attachment tray receives attachment data")
    require("frontend/react/src/components/ChatComposerForm.jsx", "knowledgeBases", "React composer owns knowledge options")
    require("frontend/react/src/components/ChatComposerForm.jsx", "selectedKnowledgeBaseId", "React composer owns selected knowledge base")
    require("frontend/react/src/components/ChatComposerForm.jsx", "sending", "React composer owns sending state")
    require("frontend/react/src/components/ChatComposerForm.jsx", "knowflow:react-knowledge-options-updated", "React composer receives knowledge options")
    require("frontend/react/src/components/ChatComposerForm.jsx", "knowflow:react-knowledge-selection-updated", "React composer receives knowledge selection")
    require("frontend/react/src/components/ChatComposerForm.jsx", "knowflow:react-sending-updated", "React composer receives sending state")
    require("frontend/react/src/components/ChatComposerForm.jsx", "handleRemoveAttachment", "React attachment remove handler")
    require("frontend/react/src/components/ChatComposerForm.jsx", "handleComposerMenuToggle", "React composer menu toggle handler")
    require("frontend/react/src/components/ChatComposerForm.jsx", "handleComposerMenuClick", "React composer menu click guard")
    require("frontend/react/src/components/ChatComposerForm.jsx", "handleChatFileChange", "React chat file change handler")
    require("frontend/react/src/components/ChatComposerForm.jsx", "handleComposerKnowledgeBaseChange", "React composer knowledge base change handler")
    require("frontend/react/src/components/ChatComposerForm.jsx", "handleChatSubmit", "React chat submit handler")
    require("frontend/react/src/components/ChatComposerForm.jsx", "handleChatInput", "React chat input handler")
    require("frontend/react/src/components/ChatComposerForm.jsx", "handleChatPaste", "React chat paste handler")
    require("frontend/react/src/components/ChatComposerForm.jsx", "handleChatKeyDown", "React chat keydown handler")
    require("frontend/react/src/components/ChatComposerForm.jsx", "menuOpen", "React composer owns menu open state")
    require("frontend/react/src/components/ChatComposerForm.jsx", "knowflow:react-composer-menu-close", "React composer menu close event")
    require("frontend/react/src/components/ChatComposerForm.jsx", "knowflow:react-chat-files-change", "React chat files event")
    require("frontend/react/src/components/ChatComposerForm.jsx", "knowflow:react-composer-kb-change", "React composer knowledge base event")
    require("frontend/react/src/components/ChatComposerForm.jsx", "knowflow:react-chat-submit", "React chat submit event")
    require("frontend/react/src/components/ChatComposerForm.jsx", "knowflow:react-attachment-remove", "React attachment remove event")
    require("frontend/react/src/components/ChatComposerForm.jsx", "knowflow:react-composer-reset", "React composer reset event")
    require("frontend/react/src/components/ChatComposerForm.jsx", "knowflow:react-chat-paste", "React chat paste event")
    require("frontend/react/src/components/ChatComposerForm.jsx", "knowflow:react-chat-enter-submit", "React chat enter event")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "chat-model-select", "chat model select id retained")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "chat-kb-select", "chat kb select id retained")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "active-session", "active session id retained")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "activeSessionId", "React active session owns state")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "chatModels", "React context toolbar owns chat model options")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "knowledgeBases", "React context toolbar owns knowledge options")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "selectedModelId", "React context toolbar owns selected model")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "selectedKnowledgeBaseId", "React context toolbar owns selected knowledge base")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "knowflow:react-active-session-updated", "React active session receives session data")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "knowflow:react-model-options-updated", "React context toolbar receives model options")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "knowflow:react-knowledge-options-updated", "React context toolbar receives knowledge options")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "knowflow:react-model-selection-updated", "React context toolbar receives model selection")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "knowflow:react-knowledge-selection-updated", "React context toolbar receives knowledge selection")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "handleChatModelChange", "React chat model handler")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "handleChatKnowledgeBaseChange", "React chat knowledge base handler")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "knowflow:react-chat-model-change", "React chat model event")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "knowflow:react-chat-kb-change", "React chat knowledge base event")
    require("frontend/react/src/components/ChatTopbar.jsx", "inspector-toggle", "inspector toggle id retained")
    require("frontend/react/src/components/ChatTopbar.jsx", "refresh-btn", "refresh button id retained")
    require("frontend/react/src/components/ChatTopbar.jsx", "knowflow:react-refresh", "React refresh event")
    require("frontend/react/src/components/ChatTopbar.jsx", "knowflow:react-drawer-toggle", "React drawer toggle event")
    require("frontend/react/src/components/ChatMessages.jsx", "chat-messages", "chat messages id retained")
    require("frontend/react/src/components/ChatMessages.jsx", "welcome-card", "welcome card retained")
    require("frontend/react/src/components/ChatMessages.jsx", "useRef", "React chat messages keeps container ref")
    require("frontend/react/src/components/ChatMessages.jsx", "useState", "React chat messages owns message state")
    require("frontend/react/src/components/ChatMessages.jsx", "flushSync", "React chat messages supports synchronous legacy bridge")
    require("frontend/react/src/components/ChatMessages.jsx", "knowflow:react-message-append", "React chat messages receives append events")
    require("frontend/react/src/components/ChatMessages.jsx", "knowflow:react-messages-reset", "React chat messages receives reset events")
    require("frontend/react/src/components/ChatMessages.jsx", "knowflow:react-message-content", "React chat messages receives content update events")
    require("frontend/react/src/components/ChatMessages.jsx", "knowflow:react-message-thinking", "React chat messages receives thinking update events")
    forbid("frontend/react/src/components/ChatMessages.jsx", "__knowflowReactMessages", "legacy global message controller")
    require("frontend/react/src/components/ChatMessages.jsx", "appendMessage", "React chat messages append controller")
    require("frontend/react/src/components/ChatMessages.jsx", "handleContent", "React chat messages content update handler")
    require("frontend/react/src/components/ChatMessages.jsx", "handleThinking", "React chat messages thinking update handler")
    require("frontend/react/src/components/ChatMessages.jsx", "resetMessages", "React chat messages reset controller")
    require("frontend/react/src/components/ChatMessages.jsx", "MessageRow", "React message row renderer")
    require("frontend/react/src/components/ChatMessages.jsx", "data-react-message-id", "React message DOM id marker")
    require("frontend/react/src/components/ChatMessages.jsx", "handleMessageActionClick", "React message action click handler")
    require("frontend/react/src/components/ChatMessages.jsx", "data-message-action", "React message action selector")
    require("frontend/react/src/components/ChatMessages.jsx", "knowflow:react-message-copy", "React message copy event")
    require("frontend/react/src/components/ChatMessages.jsx", "knowflow:react-message-retry", "React message retry event")
    forbid("frontend/react/src/controller/knowflowController.js", "__knowflowReactMessageActionsEnabled", "dead message action bridge flag")
    forbid("frontend/react/src/controller/knowflowController.js", "__knowflowReactMessageListEnabled", "dead message list bridge flag")
    require("frontend/react/src/controller/knowflowController.js", "appendReactMessage", "legacy delegates message append to React")
    require("frontend/react/src/controller/messageEvents.js", "knowflow:react-message-append", "message event module dispatches message append event")
    require("frontend/react/src/controller/messageEvents.js", "knowflow:react-messages-reset", "message event module dispatches message reset event")
    require("frontend/react/src/controller/messageEvents.js", "knowflow:react-message-content", "message event module dispatches message content event")
    require("frontend/react/src/controller/messageEvents.js", "knowflow:react-message-thinking", "message event module dispatches message thinking event")
    forbid("frontend/react/src/controller/knowflowController.js", "__knowflowReactMessages", "legacy global message controller access")
    require("frontend/react/src/controller/knowflowController.js", "updateReactMessageContent", "legacy delegates message content updates to React")
    require("frontend/react/src/controller/knowflowController.js", "updateReactMessageThinking", "legacy delegates message thinking updates to React")
    require("frontend/react/src/controller/knowflowController.js", "clearChatMessages", "controller delegates message reset to React")
    require("frontend/react/src/controller/bridgeBindings.js", "bindReactControllerEvents", "consolidated React controller bridge binder")
    require("frontend/react/src/controller/bridgeBindings.js", "knowflow:react-message-copy", "legacy message copy bridge event")
    require("frontend/react/src/controller/bridgeBindings.js", "knowflow:react-message-retry", "legacy message retry bridge event")
    require("frontend/react/src/components/ChatEvidenceDrawer.jsx", "evidence-drawer", "evidence drawer markup")
    require("frontend/react/src/components/ChatEvidenceDrawer.jsx", "reference-list", "reference list id retained")
    require("frontend/react/src/components/ChatEvidenceDrawer.jsx", "tool-timeline-mini", "tool timeline id retained")
    require("frontend/react/src/components/ChatEvidenceDrawer.jsx", "knowflow:react-drawer-close", "React drawer close event")
    require("frontend/react/src/components/ChatEvidenceDrawer.jsx", "references", "React evidence drawer owns reference state")
    require("frontend/react/src/components/ChatEvidenceDrawer.jsx", "toolCalls", "React evidence drawer owns tool call state")
    require("frontend/react/src/components/ChatEvidenceDrawer.jsx", "knowflow:react-references-updated", "React evidence drawer receives references")
    require("frontend/react/src/components/ChatEvidenceDrawer.jsx", "knowflow:react-tool-timeline-updated", "React evidence drawer receives tool timeline")
    require("frontend/react/src/components/KnowledgePage.jsx", "knowledge-workspace", "React knowledge page markup")
    require("frontend/react/src/components/KnowledgePage.jsx", "KnowledgeHeader", "knowledge page renders header component")
    require("frontend/react/src/components/KnowledgePage.jsx", "KnowledgeSummary", "knowledge page renders summary component")
    require("frontend/react/src/components/KnowledgePage.jsx", "KnowledgeRail", "knowledge page renders rail component")
    require("frontend/react/src/components/KnowledgePage.jsx", "KnowledgeDocuments", "knowledge page renders documents component")
    require("frontend/react/src/components/KnowledgePage.jsx", "KnowledgeModals", "knowledge page renders modals component")
    require("frontend/react/src/components/KnowledgePage.jsx", "KnowledgeRetrievalDrawer", "knowledge page renders retrieval drawer component")
    require("frontend/react/src/components/KnowledgePage.jsx", "KnowledgeTabBar", "React knowledge tabbar component")
    require("frontend/react/src/components/KnowledgePage.jsx", "KnowledgeSettingsPanel", "React knowledge settings panel component")
    require("frontend/react/src/components/KnowledgePage.jsx", "activeTab", "React knowledge workspace tab state")
    require("frontend/react/src/components/KnowledgePage.jsx", "knowledgeModalOpen", "React knowledge modal state")
    require("frontend/react/src/components/KnowledgePage.jsx", "setKnowledgeModalOpen", "React knowledge modal setter")
    forbid("frontend/react/src/components/KnowledgePage.jsx", "KnowledgeActionBar", "duplicated knowledge actionbar component")
    forbid("frontend/react/src/components/KnowledgePage.jsx", "knowledge-actionbar", "duplicated knowledge actionbar markup")
    require("frontend/react/src/components/KnowledgePage.jsx", "knowledge-tabbar", "React knowledge tabbar markup")
    require("frontend/react/src/components/KnowledgePage.jsx", "knowledge-settings-panel", "React knowledge settings panel markup")
    require("frontend/react/src/components/KnowledgePage.jsx", "handleOpenRetrievalDrawer", "React knowledge page opens retrieval tab")
    require("frontend/react/src/components/KnowledgePage.jsx", "handleCloseRetrievalDrawer", "React knowledge page closes retrieval tab")
    require("frontend/react/src/components/KnowledgeHeader.jsx", "open-retrieval-drawer-btn", "knowledge retrieval button id retained")
    require("frontend/react/src/components/KnowledgeHeader.jsx", "open-kb-modal-btn", "knowledge create button id retained")
    require("frontend/react/src/components/KnowledgeSummary.jsx", "kb-detail", "knowledge detail id retained")
    require("frontend/react/src/components/KnowledgeSummary.jsx", "knowledgeBases", "React knowledge detail owns knowledge base state")
    require("frontend/react/src/components/KnowledgeSummary.jsx", "models", "React knowledge detail owns model state")
    require("frontend/react/src/components/KnowledgeSummary.jsx", "selectedKnowledgeBaseId", "React knowledge detail owns selected id state")
    require("frontend/react/src/components/KnowledgeSummary.jsx", "selectedKnowledgeBase", "React knowledge detail owns selected knowledge base state")
    require("frontend/react/src/components/KnowledgeSummary.jsx", "embeddingModel", "React knowledge detail owns embedding model state")
    require("frontend/react/src/components/KnowledgeSummary.jsx", "knowflow:react-knowledge-options-updated", "React knowledge detail receives knowledge options")
    require("frontend/react/src/components/KnowledgeSummary.jsx", "knowflow:react-knowledge-selection-updated", "React knowledge detail receives knowledge selection")
    require("frontend/react/src/components/KnowledgeSummary.jsx", "knowflow:react-model-options-updated", "React knowledge detail receives model options")
    forbid("frontend/react/src/components/KnowledgeRail.jsx", "open-kb-modal-small-btn", "duplicated knowledge rail create button")
    require("frontend/react/src/components/KnowledgeRail.jsx", "kb-search-input", "knowledge search id retained")
    require("frontend/react/src/components/KnowledgeRail.jsx", "kb-list", "knowledge list id retained")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "doc-kb-select", "document kb select id retained")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "document-form", "document form id retained")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "document-drop-zone", "document drop zone id retained")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "document-file-input", "document file input id retained")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "document-list", "document list id retained")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "uploadModalOpen", "React document upload modal state")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "upload-modal", "React document upload modal markup")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "upload-modal-trigger", "React document upload trigger")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "upload-queue-summary", "React document upload flow summary")
    require("frontend/react/src/components/KnowledgePage.jsx", "uploadModalOpen", "React knowledge page owns upload modal state")
    require("frontend/react/src/components/KnowledgePage.jsx", "setUploadModalOpen", "React knowledge page controls upload modal")
    require("frontend/react/src/components/KnowledgePage.jsx", "setUploadModalOpen={setUploadModalOpen}", "document workspace controls upload modal directly")
    forbid("frontend/react/src/components/KnowledgePage.jsx", "onUploadClick", "removed duplicate upload action callback")
    require("frontend/react/src/components/KnowledgeModals.jsx", "kb-modal", "knowledge modal id retained")
    require("frontend/react/src/components/KnowledgeModals.jsx", "kb-form", "knowledge form id retained")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "chunk-modal", "chunk modal id retained")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "chunk-list", "chunk list id retained")
    require("frontend/react/src/components/KnowledgeRetrievalDrawer.jsx", "retrieval-drawer", "retrieval drawer id retained")
    require("frontend/react/src/components/KnowledgeRetrievalDrawer.jsx", "retrieval-form", "retrieval form id retained")
    require("frontend/react/src/components/KnowledgeRetrievalDrawer.jsx", "retrieval-list", "retrieval list id retained")
    require("frontend/react/src/components/KnowledgeRetrievalDrawer.jsx", "retrievalResults", "React retrieval drawer owns result state")
    require("frontend/react/src/components/KnowledgeRetrievalDrawer.jsx", "knowledgeBases", "React retrieval drawer owns knowledge options")
    require("frontend/react/src/components/KnowledgeRetrievalDrawer.jsx", "selectedKnowledgeBaseId", "React retrieval drawer owns selected knowledge base")
    require("frontend/react/src/components/KnowledgeRetrievalDrawer.jsx", "retrievalApi.debug", "React retrieval drawer loads debug results")
    require("frontend/react/src/components/KnowledgeRetrievalDrawer.jsx", "setLoading", "React retrieval drawer owns loading state")
    require("frontend/react/src/components/KnowledgeRetrievalDrawer.jsx", "knowflow:react-knowledge-options-updated", "React retrieval drawer receives knowledge options")
    require("frontend/react/src/components/KnowledgeRetrievalDrawer.jsx", "knowflow:react-knowledge-selection-updated", "React retrieval drawer receives knowledge selection")
    require("frontend/react/src/components/KnowledgeModals.jsx", "embeddingModels", "React knowledge modal owns embedding model options")
    require("frontend/react/src/components/KnowledgeModals.jsx", "selectedEmbeddingModelId", "React knowledge modal owns selected embedding model")
    require("frontend/react/src/components/KnowledgeModals.jsx", "knowflow:react-model-options-updated", "React knowledge modal receives model options")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "chunks", "React chunk modal owns chunk state")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "chunksLoading", "React chunk modal owns loading state")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "chunkModalOpen", "React chunk modal owns open state")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "setChunks", "React document list drives chunk updates")
    require("frontend/react/src/components/KnowledgeHeader.jsx", "handleOpenRetrievalDrawer", "React knowledge header retrieval handler")
    require("frontend/react/src/components/KnowledgeHeader.jsx", "handleOpenKnowledgeBaseModal", "React knowledge header create handler")
    require("frontend/react/src/components/KnowledgeHeader.jsx", "onOpenRetrievalDrawer", "React retrieval drawer open callback")
    require("frontend/react/src/components/KnowledgeHeader.jsx", "onOpenKnowledgeBaseModal", "React knowledge header modal callback")
    forbid("frontend/react/src/components/KnowledgeRail.jsx", "handleOpenKnowledgeBaseModal", "duplicate React knowledge rail create handler")
    require("frontend/react/src/components/KnowledgeRail.jsx", "handleKnowledgeSearch", "React knowledge search handler")
    require("frontend/react/src/components/KnowledgeRail.jsx", "loadKnowledgeBases", "React knowledge list loads data")
    require("frontend/react/src/components/KnowledgeRail.jsx", "knowledgeApi", "React knowledge list owns knowledge API calls")
    require("frontend/react/src/components/KnowledgeRail.jsx", "knowledgeBases", "React knowledge list state")
    require("frontend/react/src/components/KnowledgeRail.jsx", "openMenuKnowledgeBaseId", "React knowledge menu state")
    require("frontend/react/src/components/KnowledgeRail.jsx", "filteredKnowledgeBases", "React knowledge list filter")
    require("frontend/react/src/components/KnowledgeRail.jsx", "knowledgeApi.list", "React knowledge list loads data directly")
    forbid("frontend/react/src/components/KnowledgeRail.jsx", "onOpenKnowledgeBaseModal", "duplicate React rail knowledge modal callback")
    require("frontend/react/src/components/KnowledgeRail.jsx", "handleKnowledgeBaseSelect", "React knowledge select handler")
    require("frontend/react/src/components/KnowledgeRail.jsx", "handleKnowledgeBaseDelete", "React knowledge delete handler")
    require("frontend/react/src/components/KnowledgeRail.jsx", "knowflow:react-knowledge-selection-sync", "React knowledge selection sync event")
    forbid("frontend/react/src/components/KnowledgeDocuments.jsx", "handleOpenRetrievalDrawer", "dead React document retrieval handler")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "handleDocumentKnowledgeBaseChange", "React document knowledge base handler")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "handleDocumentSubmit", "React document submit handler")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "handleDocumentFileChange", "React document file change handler")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "handleDocumentDragStart", "React document drag start handler")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "handleDocumentDragEnd", "React document drag end handler")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "handleDocumentDrop", "React document drop handler")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "documents", "React document list owns document state")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "knowledgeBases", "React document upload owns knowledge options")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "selectedKnowledgeBaseId", "React document upload owns selected knowledge base")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "loadDocuments", "React document list loads documents")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "documentApi.list", "React document list API call")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "isDocumentProcessing", "React document list polling predicate")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "knowflow:react-knowledge-options-updated", "React document upload receives knowledge options")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "knowflow:react-knowledge-selection-updated", "React document upload receives knowledge selection")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "documentApi", "React document list owns document API calls")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "handleLoadDocumentChunks", "React document chunks handler")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "handleReindexDocument", "React document reindex handler")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "handleDeleteDocument", "React document delete handler")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "handlePendingDocumentRemove", "React pending document removal handler")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "handleSelectedDocumentFile", "React document file selection handler")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "documentApi.upload", "React document upload API call")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "pendingDocuments", "React document pending queue")
    forbid("frontend/react/src/components/KnowledgeDocuments.jsx", "onOpenRetrievalDrawer", "dead React document retrieval callback")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "knowflow:react-knowledge-selection-sync", "React document knowledge base sync event")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "handleChunkModalBackdrop", "React document chunk modal backdrop")
    require("frontend/react/src/components/KnowledgeModals.jsx", "handleKnowledgeModalBackdrop", "React knowledge modal backdrop handler")
    require("frontend/react/src/components/KnowledgeModals.jsx", "handleKnowledgeBaseSubmit", "React knowledge base submit handler")
    require("frontend/react/src/components/KnowledgeModals.jsx", "knowledgeModalOpen", "React knowledge modal visibility prop")
    require("frontend/react/src/components/KnowledgeModals.jsx", "setKnowledgeModalOpen(false)", "React knowledge modal close action")
    require("frontend/react/src/components/KnowledgeModals.jsx", "knowledgeApi.create", "React knowledge base create action")
    require(
        "frontend/react/src/components/KnowledgeModals.jsx",
        "knowflow:react-knowledge-bases-refresh-request",
        "React knowledge create refresh event",
    )
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "handleCloseChunkModal", "React chunk modal close handler")
    require("frontend/react/src/components/KnowledgeRetrievalDrawer.jsx", "handleCloseRetrievalDrawer", "React retrieval close handler")
    require("frontend/react/src/components/KnowledgeRetrievalDrawer.jsx", "handleRetrievalSubmit", "React retrieval submit handler")
    require("frontend/react/src/components/KnowledgeRetrievalDrawer.jsx", "onClose", "React retrieval close callback")
    require("frontend/react/src/components/KnowledgeRetrievalDrawer.jsx", "retrievalApi.debug", "React retrieval debug submit action")
    require("frontend/react/src/components/SettingsPage.jsx", "SettingsHeader", "settings page renders header component")
    require("frontend/react/src/components/SettingsPage.jsx", "ModelConfigForm", "settings page renders model form component")
    require("frontend/react/src/components/SettingsPage.jsx", "ModelListPanel", "settings page renders model list component")
    require("frontend/react/src/components/SettingsPage.jsx", "SettingsSidePanel", "settings page renders side panel component")
    require("frontend/react/src/components/ModelConfigForm.jsx", "model-form", "model form id retained")
    require("frontend/react/src/components/ModelConfigForm.jsx", "model-form-title", "model form title id retained")
    require("frontend/react/src/components/ModelProviderSelector.jsx", "provider-grid", "provider grid id retained")
    require("frontend/react/src/components/ModelConfigForm.jsx", "ModelProviderSelector", "model form renders provider selector")
    require("frontend/react/src/components/ModelProviderSelector.jsx", "provider-card", "provider cards retained")
    require("frontend/react/src/components/ModelProviderSelector.jsx", "selectedProvider", "provider selector is controlled by settings page")
    require("frontend/react/src/components/ModelProviderSelector.jsx", "onProviderSelect", "provider selector callback")
    require("frontend/react/src/components/ModelProviderSelector.jsx", "providerCards.map", "provider selector renders configured cards")
    require("frontend/react/src/components/ModelConfigForm.jsx", "model-preset-select", "model preset select id retained")
    require("frontend/react/src/components/ModelConfigForm.jsx", "model-provider", "model provider id retained")
    require("frontend/react/src/components/ModelConfigForm.jsx", "model-submit-btn", "model submit id retained")
    require("frontend/react/src/components/ModelConfigForm.jsx", "model-cancel-btn", "model cancel id retained")
    require("frontend/react/src/components/SettingsPage.jsx", "modelConfigApi", "settings page owns model API calls")
    require("frontend/react/src/components/SettingsPage.jsx", "formValues", "settings page owns model form state")
    require("frontend/react/src/components/SettingsPage.jsx", "handleModelSubmit", "React model submit handler")
    require("frontend/react/src/components/SettingsPage.jsx", "handleModelEdit", "React model edit handler")
    require("frontend/react/src/components/SettingsPage.jsx", "handleModelTest", "React model test handler")
    require("frontend/react/src/components/SettingsPage.jsx", "handleSetDefaultModel", "React default model handler")
    require("frontend/react/src/components/SettingsPage.jsx", "handleDeleteModel", "React model delete handler")
    require("frontend/react/src/components/SettingsPage.jsx", "loadModels", "settings page loads model data")
    require("frontend/react/src/components/SettingsPage.jsx", "modelConfigApi.list", "settings page loads model list API")
    require("frontend/react/src/components/SettingsPage.jsx", "knowflow:react-models-refresh-request", "settings page asks legacy data hub to refresh models")
    require("frontend/react/src/components/ModelConfigForm.jsx", "value={formValues.name}", "controlled model name input")
    require("frontend/react/src/components/ModelConfigForm.jsx", "onChange={onFieldChange}", "controlled model form input change")
    require("frontend/react/src/components/ModelConfigForm.jsx", "onSubmit={onSubmit}", "React model form submit callback")
    require("frontend/react/src/components/ModelConfigForm.jsx", "selectedPresetValue", "controlled model preset")
    require("frontend/react/src/components/ModelListPanel.jsx", "model-list", "model list id retained")
    require("frontend/react/src/components/ModelListPanel.jsx", "models = []", "React model list receives model state")
    require("frontend/react/src/components/ModelListPanel.jsx", "onModelEdit", "React model edit callback")
    require("frontend/react/src/components/ModelListPanel.jsx", "onModelTest", "React model test callback")
    require("frontend/react/src/components/ModelListPanel.jsx", "onSetDefaultModel", "React default model callback")
    require("frontend/react/src/components/ModelListPanel.jsx", "onDeleteModel", "React model delete callback")
    require("frontend/react/src/components/SettingsSidePanel.jsx", "默认模型", "settings side panel product note")
    forbid("frontend/react/src/components/SettingsSidePanel.jsx", "/docs", "settings docs link hidden from product UI")
    forbid("frontend/react/src/components/SettingsSidePanel.jsx", "/api/health", "settings health link hidden from product UI")

    forbid("frontend/react/src/main.jsx", "document.createElement", "legacy script injection in main")
    require("frontend/react/src/App.jsx", "KnowFlowController", "React controller rendered by React")
    require_file("frontend/react/src/components/KnowFlowController.jsx", "KnowFlowController component file")
    require("frontend/react/src/components/KnowFlowController.jsx", "useEffect", "React controller lifecycle")
    forbid("frontend/react/src/controller/knowflowController.js", "__knowflowReactAuthEnabled", "dead auth ownership flag")
    forbid("frontend/react/src/controller/knowflowController.js", "__knowflowReactAuthStateEnabled", "dead auth state ownership flag")
    forbid("frontend/react/src/controller/knowflowController.js", "__knowflowReactComposerEnabled", "dead composer ownership flag")
    forbid("frontend/react/src/controller/knowflowController.js", "__knowflowReactNavigationEnabled", "dead navigation ownership flag")
    forbid("frontend/react/src/controller/knowflowController.js", "__knowflowReactShellActionsEnabled", "dead shell actions ownership flag")
    forbid("frontend/react/src/controller/knowflowController.js", "__knowflowReactUserMenuEnabled", "dead user menu ownership flag")
    forbid("frontend/react/src/controller/knowflowController.js", "__knowflowReactComposerChromeEnabled", "dead composer chrome ownership flag")
    forbid("frontend/react/src/controller/knowflowController.js", "__knowflowReactContextControlsEnabled", "dead context controls ownership flag")
    forbid("frontend/react/src/controller/knowflowController.js", "__knowflowReactFormActionsEnabled", "dead form actions ownership flag")
    forbid("frontend/react/src/controller/knowflowController.js", "__knowflowReactChatInputEnabled", "dead chat input ownership flag")
    forbid("frontend/react/src/controller/knowflowController.js", "__knowflowReactKnowledgeDetailEnabled", "dead knowledge detail ownership flag")
    forbid("frontend/react/src/controller/knowflowController.js", "__knowflowReactEvidenceDrawerEnabled", "dead evidence drawer ownership flag")
    forbid("frontend/react/src/controller/knowflowController.js", "__knowflowReactModelOptionsEnabled", "dead model options ownership flag")
    forbid("frontend/react/src/controller/knowflowController.js", "__knowflowReactKnowledgeOptionsEnabled", "dead knowledge options ownership flag")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowControllerStarted", "React controller duplicate guard")
    forbid("frontend/react/src/App.jsx", "LegacyControllerBridge", "old legacy bridge import")
    forbid_file("frontend/react/src/components/LegacyControllerBridge.jsx", "old legacy bridge component")
    require("frontend/react/src/controller/bridgeBindings.js", "knowflow:react-auth-success", "legacy listens for React auth success")
    require("frontend/react/src/controller/bridgeBindings.js", "knowflow:react-auth-logout", "legacy listens for React auth logout")
    require("frontend/react/src/controller/knowflowController.js", "notifyReactAuthStateUpdated", "legacy broadcasts auth state to React")
    require("frontend/react/src/controller/reactNotifications.js", "knowflow:react-auth-state-updated", "React auth state event name")
    require("frontend/react/src/controller/bridgeBindings.js", "knowflow:react-page-change", "legacy listens for React page navigation")
    require("frontend/react/src/controller/bridgeBindings.js", "knowflow:react-new-chat", "legacy listens for React new chat")
    require("frontend/react/src/controller/bridgeBindings.js", "knowflow:react-refresh", "legacy listens for React refresh")
    require("frontend/react/src/controller/bridgeBindings.js", "knowflow:react-chat-files-change", "legacy listens for React chat files")
    require("frontend/react/src/controller/bridgeBindings.js", "knowflow:react-composer-kb-change", "legacy listens for React composer knowledge base")
    require("frontend/react/src/controller/bridgeBindings.js", "knowflow:react-chat-model-change", "legacy listens for React chat model")
    require("frontend/react/src/controller/bridgeBindings.js", "knowflow:react-chat-kb-change", "legacy listens for React chat knowledge base")
    require("frontend/react/src/controller/bridgeBindings.js", "knowflow:react-knowledge-selection-sync", "legacy receives React knowledge selection")
    require("frontend/react/src/controller/bridgeBindings.js", "knowflow:react-knowledge-bases-sync", "legacy receives React knowledge list data")
    require("frontend/react/src/controller/bridgeBindings.js", "knowflow:react-chat-submit", "legacy listens for React chat submit")
    require("frontend/react/src/controller/bridgeBindings.js", "knowflow:react-chat-paste", "legacy listens for React chat paste")
    require("frontend/react/src/controller/bridgeBindings.js", "knowflow:react-chat-enter-submit", "legacy listens for React chat enter")
    require("frontend/react/src/controller/bridgeBindings.js", "knowflow:react-models-refresh-request", "legacy refreshes model data on React request")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-references-updated", "controller broadcasts references to React")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-tool-timeline-updated", "controller broadcasts tool timeline to React")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-attachments-updated", "controller broadcasts attachments to React")
    require("frontend/react/src/controller/knowflowController.js", "notifyReactModelOptionsUpdated", "legacy broadcasts model options to React")
    require("frontend/react/src/controller/knowflowController.js", "notifyReactKnowledgeOptionsUpdated", "legacy broadcasts knowledge options to React")
    require("frontend/react/src/controller/knowflowController.js", "notifyReactModelSelectionUpdated", "legacy broadcasts model selection to React")
    require("frontend/react/src/controller/knowflowController.js", "notifyReactKnowledgeSelectionUpdated", "legacy broadcasts knowledge selection to React")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-sending-updated", "legacy emits React sending state")
    require("frontend/react/src/controller/reactNotifications.js", "knowflow:react-toast", "controller emits React toast event")
    require("frontend/react/src/controller/bridgeBindings.js", "knowflow:react-attachment-remove", "legacy listens for React attachment remove")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-active-session-updated", "controller broadcasts active session to React")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-sessions-refresh-request", "legacy asks React to refresh session data")
    require("frontend/react/src/controller/bridgeBindings.js", "knowflow:react-session-continue", "legacy listens for React session continue")
    forbid("frontend/react/src/controller/knowflowController.js", "if (!window.__knowflowReactAuthEnabled)", "dead auth DOM binding guard")
    forbid("frontend/react/src/controller/knowflowController.js", "prompt-chip", "legacy prompt chip binding")
    forbid("frontend/react/src/controller/knowflowController.js", "ReactToolControls", "legacy manual tool ownership")
    forbid("frontend/react/src/controller/knowflowController.js", "react-tool-mode-change", "manual tool mode bridge")
    forbid("frontend/react/src/controller/knowflowController.js", "react-tool-selection-change", "manual tool selection bridge")
    forbid("frontend/react/src/controller/knowflowController.js", "if (!window.__knowflowReactNavigationEnabled)", "dead page navigation DOM binding guard")
    forbid("frontend/react/src/controller/knowflowController.js", "if (!window.__knowflowReactShellActionsEnabled)", "dead shell actions DOM binding guard")
    forbid("frontend/react/src/controller/knowflowController.js", "if (!window.__knowflowReactUserMenuEnabled)", "dead user menu DOM binding guard")
    forbid("frontend/react/src/controller/knowflowController.js", "if (!window.__knowflowReactComposerChromeEnabled)", "dead composer chrome DOM binding guard")
    forbid("frontend/react/src/controller/knowflowController.js", "if (!window.__knowflowReactContextControlsEnabled)", "dead context controls DOM binding guard")
    forbid("frontend/react/src/controller/knowflowController.js", "if (!window.__knowflowReactFormActionsEnabled)", "dead form actions DOM binding guard")
    forbid("frontend/react/src/controller/knowflowController.js", "if (!window.__knowflowReactChatInputEnabled)", "dead chat input DOM binding guard")
    forbid("frontend/react/src/controller/knowflowController.js", "knowflow:react-document-kb-change", "dead document knowledge bridge")
    forbid("frontend/react/src/controller/knowflowController.js", "knowflow:react-documents-refresh-request", "dead document refresh bridge")
    forbid("frontend/react/src/controller/knowflowController.js", "function renderKnowledgeBaseDetail", "dead knowledge detail renderer")
    forbid("frontend/react/src/controller/knowflowController.js", "legacy-knowledge-detail-updated", "dead knowledge detail event")
    forbid("frontend/react/src/controller/knowflowController.js", "__knowflowReactEvidenceDrawerEnabled", "dead evidence drawer ownership flag")
    forbid("frontend/react/src/controller/knowflowController.js", "__knowflowReactAttachmentTrayEnabled", "dead attachment-tray ownership flag")
    forbid("frontend/react/src/controller/knowflowController.js", "__knowflowReactActiveSessionEnabled", "dead active-session ownership flag")

    forbid_file("frontend/react/src/legacyTemplate.js", "legacy template after React component extraction")
    require("frontend/react/src/controller/knowflowController.js", "bootstrap", "legacy controller bridge")

    readme = read("README.md")
    for token in ["闁?", "缂?", "閻?", "濞戞挴鍋?"]:
        if token in readme:
            raise AssertionError(f"README still contains mojibake token: {token}")


if __name__ == "__main__":
    main()


