from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


def require(path: str, needle: str, label: str) -> None:
    text = read(path)
    if needle not in text:
        raise AssertionError(f"missing {label} in {path}: {needle}")


def forbid(path: str, needle: str, label: str) -> None:
    text = read(path)
    if needle in text:
        raise AssertionError(f"unexpected {label} in {path}: {needle}")


def require_file(path: str, label: str) -> None:
    if not (ROOT / path).exists():
        raise AssertionError(f"missing {label}: {path}")


def forbid_file(path: str, label: str) -> None:
    if (ROOT / path).exists():
        raise AssertionError(f"unexpected {label}: {path}")


def main() -> None:
    require("frontend/package.json", '"react"', "React dependency")
    require("frontend/package.json", '"vite"', "Vite dependency")
    require("frontend/vite.config.js", 'root: "react"', "React app root")
    require("frontend/vite.config.js", 'outDir: "../dist"', "Vite build output")
    require("frontend/react/src/main.jsx", "createRoot", "React mount")
    require_file("frontend/react/src/api/client.js", "React API client")
    require("frontend/react/src/api/client.js", "export async function apiRequest", "apiRequest helper")
    require("frontend/react/src/api/client.js", "credentials: \"include\"", "cookie credentials")
    require("frontend/react/src/api/client.js", "throw new ApiError", "structured API errors")
    require_file("frontend/react/src/auth/AuthProvider.jsx", "AuthProvider scaffold")
    require_file("frontend/react/src/data/navigation.js", "React navigation data module")
    require("frontend/react/src/data/navigation.js", "export const sidebarTools", "sidebar tool config")
    forbid("frontend/react/src/data/navigation.js", "manualToolOptions", "redundant manual tool config")
    forbid("frontend/react/src/data/navigation.js", "promptSuggestions", "redundant prompt suggestion config")
    require("frontend/react/src/auth/AuthProvider.jsx", "createContext", "auth context")
    require("frontend/react/src/auth/AuthProvider.jsx", "export function AuthProvider", "AuthProvider export")
    require("frontend/react/src/auth/AuthProvider.jsx", "export function useAuth", "useAuth export")
    require("frontend/react/src/auth/AuthProvider.jsx", "getCurrentUser", "current user loader")
    require("frontend/react/src/auth/AuthProvider.jsx", "login", "auth login action")
    require("frontend/react/src/auth/AuthProvider.jsx", "register", "auth register action")
    require("frontend/react/src/auth/AuthProvider.jsx", "logout", "auth logout action")
    require("frontend/react/src/auth/AuthProvider.jsx", "applyLegacyAuthState", "auth provider receives legacy auth state")
    require("frontend/react/src/auth/AuthProvider.jsx", "knowflow:legacy-auth-state-updated", "auth provider listens for legacy auth state")
    require("frontend/react/src/main.jsx", "AuthProvider", "AuthProvider mounted")
    require("frontend/react/src/App.jsx", "WorkbenchShell", "React shell component")

    app_source = read("frontend/react/src/App.jsx")
    if "dangerouslySetInnerHTML" in app_source:
        raise AssertionError("React shell should not use dangerouslySetInnerHTML")
    if "legacyTemplate" in app_source:
        raise AssertionError("React shell should not import legacyTemplate")

    for component_name in ["AuthScreen", "Sidebar", "ChatPage", "KnowledgePage", "SettingsPage", "Toast"]:
        require("frontend/react/src/App.jsx", f"import {{ {component_name} }}", f"{component_name} import")
        require_file(f"frontend/react/src/components/{component_name}.jsx", f"{component_name} component file")
        require(f"frontend/react/src/components/{component_name}.jsx", f"export function {component_name}", f"{component_name} named export")
        forbid("frontend/react/src/App.jsx", f"function {component_name}", f"inline {component_name} component")

    require("frontend/react/src/components/Toast.jsx", "useState", "React toast owns message state")
    require("frontend/react/src/components/Toast.jsx", "visible", "React toast owns visibility state")
    require("frontend/react/src/components/Toast.jsx", "knowflow:legacy-toast", "React toast receives legacy toast data")
    require("frontend/react/src/components/Toast.jsx", "toastTimerRef", "React toast owns hide timer")

    require_file("frontend/react/src/components/ChatComposerForm.jsx", "ChatComposerForm component file")
    require("frontend/react/src/components/ChatComposerForm.jsx", "export function ChatComposerForm", "ChatComposerForm named export")
    require_file("frontend/react/src/components/ChatContextToolbar.jsx", "ChatContextToolbar component file")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "export function ChatContextToolbar", "ChatContextToolbar named export")
    require_file("frontend/react/src/components/ChatTopbar.jsx", "ChatTopbar component file")
    require("frontend/react/src/components/ChatTopbar.jsx", "export function ChatTopbar", "ChatTopbar named export")
    require_file("frontend/react/src/components/ChatMessages.jsx", "ChatMessages component file")
    require("frontend/react/src/components/ChatMessages.jsx", "export function ChatMessages", "ChatMessages named export")
    require_file("frontend/react/src/components/ChatEvidenceDrawer.jsx", "ChatEvidenceDrawer component file")
    require("frontend/react/src/components/ChatEvidenceDrawer.jsx", "export function ChatEvidenceDrawer", "ChatEvidenceDrawer named export")
    require_file("frontend/react/src/components/KnowledgeHeader.jsx", "KnowledgeHeader component file")
    require("frontend/react/src/components/KnowledgeHeader.jsx", "export function KnowledgeHeader", "KnowledgeHeader named export")
    require_file("frontend/react/src/components/KnowledgeSummary.jsx", "KnowledgeSummary component file")
    require("frontend/react/src/components/KnowledgeSummary.jsx", "export function KnowledgeSummary", "KnowledgeSummary named export")
    require_file("frontend/react/src/components/KnowledgeRail.jsx", "KnowledgeRail component file")
    require("frontend/react/src/components/KnowledgeRail.jsx", "export function KnowledgeRail", "KnowledgeRail named export")
    require_file("frontend/react/src/components/KnowledgeDocuments.jsx", "KnowledgeDocuments component file")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "export function KnowledgeDocuments", "KnowledgeDocuments named export")
    require_file("frontend/react/src/components/KnowledgeModals.jsx", "KnowledgeModals component file")
    require("frontend/react/src/components/KnowledgeModals.jsx", "export function KnowledgeModals", "KnowledgeModals named export")
    require_file("frontend/react/src/components/KnowledgeRetrievalDrawer.jsx", "KnowledgeRetrievalDrawer component file")
    require("frontend/react/src/components/KnowledgeRetrievalDrawer.jsx", "export function KnowledgeRetrievalDrawer", "KnowledgeRetrievalDrawer named export")
    require_file("frontend/react/src/components/SettingsHeader.jsx", "SettingsHeader component file")
    require("frontend/react/src/components/SettingsHeader.jsx", "export function SettingsHeader", "SettingsHeader named export")
    require_file("frontend/react/src/components/ModelConfigForm.jsx", "ModelConfigForm component file")
    require("frontend/react/src/components/ModelConfigForm.jsx", "export function ModelConfigForm", "ModelConfigForm named export")
    require_file("frontend/react/src/components/ModelProviderSelector.jsx", "ModelProviderSelector component file")
    require("frontend/react/src/components/ModelProviderSelector.jsx", "export function ModelProviderSelector", "ModelProviderSelector named export")
    require_file("frontend/react/src/components/ModelListPanel.jsx", "ModelListPanel component file")
    require("frontend/react/src/components/ModelListPanel.jsx", "export function ModelListPanel", "ModelListPanel named export")
    require_file("frontend/react/src/components/SettingsSidePanel.jsx", "SettingsSidePanel component file")
    require("frontend/react/src/components/SettingsSidePanel.jsx", "export function SettingsSidePanel", "SettingsSidePanel named export")
    require_file("frontend/react/src/data/settings.js", "settings data module")
    require("frontend/react/src/data/settings.js", "export const providerCards", "provider card config")

    require("frontend/react/src/components/AuthScreen.jsx", "auth-screen", "React auth screen markup")
    require("frontend/react/src/components/AuthScreen.jsx", "useAuth", "auth screen consumes auth provider state")
    require("frontend/react/src/components/AuthScreen.jsx", "authenticated", "auth screen uses authenticated state")
    require("frontend/react/src/components/AuthScreen.jsx", "loading", "auth screen uses loading state")
    require("frontend/react/src/components/AuthScreen.jsx", "authScreenClassName", "auth screen dynamic visibility class")
    require("frontend/react/src/components/AuthScreen.jsx", "document.body.classList.toggle", "auth screen body lock sync")
    require("frontend/react/src/components/AuthScreen.jsx", "useState", "auth screen owns mode state")
    require("frontend/react/src/components/AuthScreen.jsx", "setMode", "auth mode setter")
    require("frontend/react/src/components/AuthScreen.jsx", "handleLogin", "React login submit handler")
    require("frontend/react/src/components/AuthScreen.jsx", "handleRegister", "React register submit handler")
    require("frontend/react/src/components/AuthScreen.jsx", "onSubmit={handleLogin}", "login form wired to React submit")
    require("frontend/react/src/components/AuthScreen.jsx", "onSubmit={handleRegister}", "register form wired to React submit")
    require("frontend/react/src/components/AuthScreen.jsx", "knowflow:react-auth-success", "React auth success event")
    require("frontend/react/src/components/AuthScreen.jsx", "knowflow:react-toast", "React auth toast event")
    require("frontend/react/src/components/AuthScreen.jsx", "oauthProviders", "OAuth provider state")
    require("frontend/react/src/components/Sidebar.jsx", "function UserMenu", "isolated user menu component")
    require("frontend/react/src/components/Sidebar.jsx", "function SessionHistory", "isolated session history component")
    require("frontend/react/src/components/Sidebar.jsx", "knowflow:legacy-sessions-updated", "React session list receives legacy data")
    require("frontend/react/src/components/Sidebar.jsx", "groupSessions", "React session list groups sessions")
    require("frontend/react/src/components/Sidebar.jsx", "filteredSessions", "React session list filters sessions")
    require("frontend/react/src/components/Sidebar.jsx", "openMenuSessionId", "React session menu state")
    require("frontend/react/src/components/Sidebar.jsx", "knowflow:react-session-continue", "React session continue event")
    require("frontend/react/src/components/Sidebar.jsx", "knowflow:react-session-rename", "React session rename event")
    require("frontend/react/src/components/Sidebar.jsx", "knowflow:react-session-delete", "React session delete event")
    require("frontend/react/src/components/Sidebar.jsx", "useAuth", "user menu consumes auth provider state")
    require("frontend/react/src/components/Sidebar.jsx", "menuOpen", "React user menu owns open state")
    require("frontend/react/src/components/Sidebar.jsx", "handleUserMenuToggle", "React user menu toggle handler")
    require("frontend/react/src/components/Sidebar.jsx", "handleLogout", "React logout handler")
    require("frontend/react/src/components/Sidebar.jsx", "knowflow:react-auth-logout", "React logout event")
    require("frontend/react/src/components/Sidebar.jsx", "avatarUrl", "user menu renders avatar from auth state")
    require("frontend/react/src/components/Sidebar.jsx", "handlePageChange", "React sidebar page handler")
    require("frontend/react/src/components/Sidebar.jsx", "knowflow:react-page-change", "React page navigation event")
    require("frontend/react/src/components/Sidebar.jsx", "handleNewChat", "React new chat handler")
    require("frontend/react/src/components/Sidebar.jsx", "knowflow:react-new-chat", "React new chat event")
    require("frontend/react/src/components/Sidebar.jsx", "handleSidebarToggle", "React sidebar toggle handler")
    require("frontend/react/src/components/Sidebar.jsx", "knowflow:react-sidebar-toggle", "React sidebar toggle event")
    require("frontend/react/src/components/Sidebar.jsx", "handleHistoryRefresh", "React history refresh handler")
    require("frontend/react/src/components/Sidebar.jsx", "knowflow:react-history-refresh", "React history refresh event")
    require("frontend/react/src/components/Sidebar.jsx", "handleSessionSearch", "React session search handler")
    require("frontend/react/src/components/Sidebar.jsx", "knowflow:react-session-search-change", "React session search event")
    require("frontend/react/src/components/Sidebar.jsx", "sidebarTools.map", "sidebar renders configured tools")
    require("frontend/react/src/components/Sidebar.jsx", "function RuntimeStatus", "React runtime status component")
    require("frontend/react/src/components/Sidebar.jsx", "knowflow:legacy-runtime-updated", "React runtime status receives legacy data")
    require("frontend/react/src/components/Sidebar.jsx", "knowflow:legacy-runtime-failed", "React runtime status receives legacy errors")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowReactRuntimeStatusEnabled", "React runtime status bridge flag")
    require("frontend/react/src/controller/knowflowController.js", "notifyReactRuntimeUpdated", "legacy runtime update notifier")
    require("frontend/react/src/controller/knowflowController.js", "notifyReactRuntimeFailed", "legacy runtime error notifier")
    require("frontend/react/src/components/ChatPage.jsx", "ChatTopbar", "chat page renders topbar component")
    require("frontend/react/src/components/ChatPage.jsx", "ChatMessages", "chat page renders messages component")
    require("frontend/react/src/components/ChatPage.jsx", "ChatContextToolbar", "chat page renders context toolbar component")
    require("frontend/react/src/components/ChatPage.jsx", "ChatComposerForm", "chat page renders composer form component")
    require("frontend/react/src/components/ChatPage.jsx", "ChatEvidenceDrawer", "chat page renders evidence drawer component")
    forbid("frontend/react/src/components/ChatComposerForm.jsx", "ChatToolControls", "redundant manual tool controls")
    forbid("frontend/react/src/components/ChatPage.jsx", "import { ChatComposer }", "redundant prompt shelf import")
    forbid("frontend/react/src/components/ChatPage.jsx", "<ChatComposer />", "redundant prompt shelf component")
    require("frontend/react/src/components/ChatComposerForm.jsx", "chat-form", "composer form id retained")
    require("frontend/react/src/components/ChatComposerForm.jsx", "composer-plus-btn", "composer plus id retained")
    require("frontend/react/src/components/ChatComposerForm.jsx", "composer-menu", "composer menu id retained")
    require("frontend/react/src/components/ChatComposerForm.jsx", "chat-file-input", "chat file input id retained")
    require("frontend/react/src/components/ChatComposerForm.jsx", "composer-kb-select", "composer kb select id retained")
    require("frontend/react/src/components/ChatComposerForm.jsx", "chat-submit-btn", "chat submit id retained")
    require("frontend/react/src/components/ChatComposerForm.jsx", "attachments", "React attachment tray owns attachment state")
    require("frontend/react/src/components/ChatComposerForm.jsx", "knowflow:legacy-attachments-updated", "React attachment tray receives legacy attachment data")
    require("frontend/react/src/components/ChatComposerForm.jsx", "knowledgeBases", "React composer owns knowledge options")
    require("frontend/react/src/components/ChatComposerForm.jsx", "selectedKnowledgeBaseId", "React composer owns selected knowledge base")
    require("frontend/react/src/components/ChatComposerForm.jsx", "sending", "React composer owns sending state")
    require("frontend/react/src/components/ChatComposerForm.jsx", "knowflow:legacy-knowledge-options-updated", "React composer receives knowledge options")
    require("frontend/react/src/components/ChatComposerForm.jsx", "knowflow:legacy-knowledge-selection-updated", "React composer receives knowledge selection")
    require("frontend/react/src/components/ChatComposerForm.jsx", "knowflow:legacy-sending-updated", "React composer receives sending state")
    require("frontend/react/src/components/ChatComposerForm.jsx", "handleRemoveAttachment", "React attachment remove handler")
    require("frontend/react/src/components/ChatComposerForm.jsx", "handleComposerMenuToggle", "React composer menu toggle handler")
    require("frontend/react/src/components/ChatComposerForm.jsx", "handleComposerMenuClick", "React composer menu click guard")
    require("frontend/react/src/components/ChatComposerForm.jsx", "handleChatFileChange", "React chat file change handler")
    require("frontend/react/src/components/ChatComposerForm.jsx", "handleComposerKnowledgeBaseChange", "React composer knowledge base change handler")
    require("frontend/react/src/components/ChatComposerForm.jsx", "handleChatSubmit", "React chat submit handler")
    require("frontend/react/src/components/ChatComposerForm.jsx", "handleChatInput", "React chat input handler")
    require("frontend/react/src/components/ChatComposerForm.jsx", "handleChatPaste", "React chat paste handler")
    require("frontend/react/src/components/ChatComposerForm.jsx", "handleChatKeyDown", "React chat keydown handler")
    require("frontend/react/src/components/ChatComposerForm.jsx", "knowflow:react-composer-menu-toggle", "React composer menu toggle event")
    require("frontend/react/src/components/ChatComposerForm.jsx", "knowflow:react-composer-menu-close", "React composer menu close event")
    require("frontend/react/src/components/ChatComposerForm.jsx", "knowflow:react-chat-files-change", "React chat files event")
    require("frontend/react/src/components/ChatComposerForm.jsx", "knowflow:react-composer-kb-change", "React composer knowledge base event")
    require("frontend/react/src/components/ChatComposerForm.jsx", "knowflow:react-chat-submit", "React chat submit event")
    require("frontend/react/src/components/ChatComposerForm.jsx", "knowflow:react-attachment-remove", "React attachment remove event")
    require("frontend/react/src/components/ChatComposerForm.jsx", "knowflow:react-chat-input", "React chat input event")
    require("frontend/react/src/components/ChatComposerForm.jsx", "knowflow:react-chat-paste", "React chat paste event")
    require("frontend/react/src/components/ChatComposerForm.jsx", "knowflow:react-chat-enter-submit", "React chat enter event")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "chat-model-select", "chat model select id retained")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "chat-kb-select", "chat kb select id retained")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "active-session", "active session id retained")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "activeSessionId", "React active session owns state")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "chatModels", "React context toolbar owns chat model options")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "knowledgeBases", "React context toolbar owns knowledge options")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "selectedModelId", "React context toolbar owns selected model")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "selectedKnowledgeBaseId", "React context toolbar owns selected knowledge base")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "knowflow:legacy-active-session-updated", "React active session receives legacy data")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "knowflow:legacy-model-options-updated", "React context toolbar receives model options")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "knowflow:legacy-knowledge-options-updated", "React context toolbar receives knowledge options")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "knowflow:legacy-model-selection-updated", "React context toolbar receives model selection")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "knowflow:legacy-knowledge-selection-updated", "React context toolbar receives knowledge selection")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "handleChatModelChange", "React chat model handler")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "handleChatKnowledgeBaseChange", "React chat knowledge base handler")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "knowflow:react-chat-model-change", "React chat model event")
    require("frontend/react/src/components/ChatContextToolbar.jsx", "knowflow:react-chat-kb-change", "React chat knowledge base event")
    require("frontend/react/src/components/ChatTopbar.jsx", "inspector-toggle", "inspector toggle id retained")
    require("frontend/react/src/components/ChatTopbar.jsx", "refresh-btn", "refresh button id retained")
    require("frontend/react/src/components/ChatTopbar.jsx", "knowflow:react-refresh", "React refresh event")
    require("frontend/react/src/components/ChatTopbar.jsx", "knowflow:react-drawer-toggle", "React drawer toggle event")
    require("frontend/react/src/components/ChatMessages.jsx", "chat-messages", "chat messages id retained")
    require("frontend/react/src/components/ChatMessages.jsx", "welcome-card", "welcome card retained")
    require("frontend/react/src/components/ChatMessages.jsx", "useRef", "React chat messages keeps container ref")
    require("frontend/react/src/components/ChatMessages.jsx", "useState", "React chat messages owns message state")
    require("frontend/react/src/components/ChatMessages.jsx", "flushSync", "React chat messages supports synchronous legacy bridge")
    require("frontend/react/src/components/ChatMessages.jsx", "__knowflowReactMessages", "React chat messages exposes legacy-safe controller")
    require("frontend/react/src/components/ChatMessages.jsx", "appendMessage", "React chat messages append controller")
    require("frontend/react/src/components/ChatMessages.jsx", "setMessageContent", "React chat messages content update controller")
    require("frontend/react/src/components/ChatMessages.jsx", "setMessageThinking", "React chat messages thinking update controller")
    require("frontend/react/src/components/ChatMessages.jsx", "resetMessages", "React chat messages reset controller")
    require("frontend/react/src/components/ChatMessages.jsx", "MessageRow", "React message row renderer")
    require("frontend/react/src/components/ChatMessages.jsx", "data-react-message-id", "React message DOM id marker")
    require("frontend/react/src/components/ChatMessages.jsx", "handleMessageActionClick", "React message action click handler")
    require("frontend/react/src/components/ChatMessages.jsx", "data-message-action", "React message action selector")
    require("frontend/react/src/components/ChatMessages.jsx", "knowflow:react-message-copy", "React message copy event")
    require("frontend/react/src/components/ChatMessages.jsx", "knowflow:react-message-retry", "React message retry event")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowReactMessageActionsEnabled", "React message action bridge flag")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowReactMessageListEnabled", "React message list bridge flag")
    require("frontend/react/src/controller/knowflowController.js", "appendReactMessage", "legacy delegates message append to React")
    require("frontend/react/src/controller/knowflowController.js", "updateReactMessageContent", "legacy delegates message content updates to React")
    require("frontend/react/src/controller/knowflowController.js", "updateReactMessageThinking", "legacy delegates message thinking updates to React")
    require("frontend/react/src/controller/knowflowController.js", "resetReactChatMessages", "legacy delegates message reset to React")
    require("frontend/react/src/controller/knowflowController.js", "bindReactMessageActionsBridge", "legacy message action bridge binder")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-message-copy", "legacy message copy bridge event")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-message-retry", "legacy message retry bridge event")
    require("frontend/react/src/components/ChatEvidenceDrawer.jsx", "evidence-drawer", "evidence drawer markup")
    require("frontend/react/src/components/ChatEvidenceDrawer.jsx", "reference-list", "reference list id retained")
    require("frontend/react/src/components/ChatEvidenceDrawer.jsx", "tool-timeline-mini", "tool timeline id retained")
    require("frontend/react/src/components/ChatEvidenceDrawer.jsx", "knowflow:react-drawer-close", "React drawer close event")
    require("frontend/react/src/components/ChatEvidenceDrawer.jsx", "references", "React evidence drawer owns reference state")
    require("frontend/react/src/components/ChatEvidenceDrawer.jsx", "toolCalls", "React evidence drawer owns tool call state")
    require("frontend/react/src/components/ChatEvidenceDrawer.jsx", "knowflow:legacy-references-updated", "React evidence drawer receives references")
    require("frontend/react/src/components/ChatEvidenceDrawer.jsx", "knowflow:legacy-tool-timeline-updated", "React evidence drawer receives tool timeline")
    require("frontend/react/src/components/KnowledgePage.jsx", "knowledge-workspace", "React knowledge page markup")
    require("frontend/react/src/components/KnowledgePage.jsx", "KnowledgeHeader", "knowledge page renders header component")
    require("frontend/react/src/components/KnowledgePage.jsx", "KnowledgeSummary", "knowledge page renders summary component")
    require("frontend/react/src/components/KnowledgePage.jsx", "KnowledgeRail", "knowledge page renders rail component")
    require("frontend/react/src/components/KnowledgePage.jsx", "KnowledgeDocuments", "knowledge page renders documents component")
    require("frontend/react/src/components/KnowledgePage.jsx", "KnowledgeModals", "knowledge page renders modals component")
    require("frontend/react/src/components/KnowledgePage.jsx", "KnowledgeRetrievalDrawer", "knowledge page renders retrieval drawer component")
    require("frontend/react/src/components/KnowledgePage.jsx", "KnowledgeActionBar", "React knowledge actionbar component")
    require("frontend/react/src/components/KnowledgePage.jsx", "KnowledgeTabBar", "React knowledge tabbar component")
    require("frontend/react/src/components/KnowledgePage.jsx", "KnowledgeSettingsPanel", "React knowledge settings panel component")
    require("frontend/react/src/components/KnowledgePage.jsx", "activeTab", "React knowledge workspace tab state")
    require("frontend/react/src/components/KnowledgePage.jsx", "knowledge-actionbar", "React knowledge actionbar markup")
    require("frontend/react/src/components/KnowledgePage.jsx", "knowledge-tabbar", "React knowledge tabbar markup")
    require("frontend/react/src/components/KnowledgePage.jsx", "knowledge-settings-panel", "React knowledge settings panel markup")
    require("frontend/react/src/components/KnowledgePage.jsx", "knowflow:legacy-knowledge-tab-change", "React knowledge page receives legacy tab changes")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowReactKnowledgeWorkspaceEnabled", "React knowledge workspace bridge flag")
    require("frontend/react/src/controller/knowflowController.js", "notifyReactKnowledgeTabChange", "legacy knowledge tab change notifier")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowReactKnowledgeWorkspaceEnabled", "legacy skips dynamic knowledge workspace when React owns it")
    require("frontend/react/src/components/KnowledgeHeader.jsx", "open-retrieval-drawer-btn", "knowledge retrieval button id retained")
    require("frontend/react/src/components/KnowledgeHeader.jsx", "open-kb-modal-btn", "knowledge create button id retained")
    require("frontend/react/src/components/KnowledgeSummary.jsx", "kb-detail", "knowledge detail id retained")
    require("frontend/react/src/components/KnowledgeSummary.jsx", "selectedKnowledgeBase", "React knowledge detail owns selected knowledge base state")
    require("frontend/react/src/components/KnowledgeSummary.jsx", "embeddingModel", "React knowledge detail owns embedding model state")
    require("frontend/react/src/components/KnowledgeSummary.jsx", "knowflow:legacy-knowledge-detail-updated", "React knowledge detail receives legacy data")
    require("frontend/react/src/components/KnowledgeRail.jsx", "open-kb-modal-small-btn", "knowledge small create button id retained")
    require("frontend/react/src/components/KnowledgeRail.jsx", "kb-search-input", "knowledge search id retained")
    require("frontend/react/src/components/KnowledgeRail.jsx", "kb-list", "knowledge list id retained")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "doc-kb-select", "document kb select id retained")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "document-form", "document form id retained")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "document-drop-zone", "document drop zone id retained")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "document-file-input", "document file input id retained")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "document-list", "document list id retained")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "uploadModalOpen", "React document upload modal state")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "upload-modal", "React document upload modal markup")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "upload-modal-trigger", "React document upload trigger")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "upload-queue-summary", "React document upload flow summary")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "knowflow:legacy-upload-modal-open", "React upload modal receives legacy open event")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "knowflow:legacy-upload-modal-close", "React upload modal receives legacy close event")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowReactUploadModalEnabled", "React upload modal bridge flag")
    require("frontend/react/src/controller/knowflowController.js", "notifyReactUploadModalOpen", "legacy upload modal open notifier")
    require("frontend/react/src/controller/knowflowController.js", "notifyReactUploadModalClose", "legacy upload modal close notifier")
    require("frontend/react/src/components/KnowledgeModals.jsx", "kb-modal", "knowledge modal id retained")
    require("frontend/react/src/components/KnowledgeModals.jsx", "kb-form", "knowledge form id retained")
    require("frontend/react/src/components/KnowledgeModals.jsx", "chunk-modal", "chunk modal id retained")
    require("frontend/react/src/components/KnowledgeModals.jsx", "chunk-list", "chunk list id retained")
    require("frontend/react/src/components/KnowledgeRetrievalDrawer.jsx", "retrieval-drawer", "retrieval drawer id retained")
    require("frontend/react/src/components/KnowledgeRetrievalDrawer.jsx", "retrieval-form", "retrieval form id retained")
    require("frontend/react/src/components/KnowledgeRetrievalDrawer.jsx", "retrieval-list", "retrieval list id retained")
    require("frontend/react/src/components/KnowledgeRetrievalDrawer.jsx", "retrievalResults", "React retrieval drawer owns result state")
    require("frontend/react/src/components/KnowledgeRetrievalDrawer.jsx", "knowledgeBases", "React retrieval drawer owns knowledge options")
    require("frontend/react/src/components/KnowledgeRetrievalDrawer.jsx", "selectedKnowledgeBaseId", "React retrieval drawer owns selected knowledge base")
    require("frontend/react/src/components/KnowledgeRetrievalDrawer.jsx", "knowflow:legacy-retrieval-results-updated", "React retrieval drawer receives result data")
    require("frontend/react/src/components/KnowledgeRetrievalDrawer.jsx", "knowflow:legacy-retrieval-loading", "React retrieval drawer receives loading state")
    require("frontend/react/src/components/KnowledgeRetrievalDrawer.jsx", "knowflow:legacy-knowledge-options-updated", "React retrieval drawer receives knowledge options")
    require("frontend/react/src/components/KnowledgeRetrievalDrawer.jsx", "knowflow:legacy-knowledge-selection-updated", "React retrieval drawer receives knowledge selection")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowReactRetrievalResultsEnabled", "React retrieval results bridge flag")
    require("frontend/react/src/controller/knowflowController.js", "notifyReactRetrievalLoading", "legacy retrieval loading notifier")
    require("frontend/react/src/controller/knowflowController.js", "notifyReactRetrievalResultsUpdated", "legacy retrieval results notifier")
    require("frontend/react/src/components/KnowledgeModals.jsx", "chunks", "React chunk modal owns chunk state")
    require("frontend/react/src/components/KnowledgeModals.jsx", "embeddingModels", "React knowledge modal owns embedding model options")
    require("frontend/react/src/components/KnowledgeModals.jsx", "selectedEmbeddingModelId", "React knowledge modal owns selected embedding model")
    require("frontend/react/src/components/KnowledgeModals.jsx", "knowflow:legacy-model-options-updated", "React knowledge modal receives model options")
    require("frontend/react/src/components/KnowledgeModals.jsx", "knowflow:legacy-chunks-updated", "React chunk modal receives chunk data")
    require("frontend/react/src/components/KnowledgeModals.jsx", "knowflow:legacy-chunks-loading", "React chunk modal receives loading state")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowReactChunkListEnabled", "React chunk list bridge flag")
    require("frontend/react/src/controller/knowflowController.js", "notifyReactChunksLoading", "legacy chunk loading notifier")
    require("frontend/react/src/controller/knowflowController.js", "notifyReactChunksUpdated", "legacy chunk update notifier")
    require("frontend/react/src/components/KnowledgeHeader.jsx", "handleOpenRetrievalDrawer", "React knowledge header retrieval handler")
    require("frontend/react/src/components/KnowledgeHeader.jsx", "handleOpenKnowledgeBaseModal", "React knowledge header create handler")
    require("frontend/react/src/components/KnowledgeHeader.jsx", "knowflow:react-open-retrieval-drawer", "React retrieval drawer open event")
    require("frontend/react/src/components/KnowledgeHeader.jsx", "knowflow:react-open-kb-modal", "React knowledge modal open event")
    require("frontend/react/src/components/KnowledgeRail.jsx", "handleOpenKnowledgeBaseModal", "React knowledge rail create handler")
    require("frontend/react/src/components/KnowledgeRail.jsx", "handleKnowledgeSearch", "React knowledge search handler")
    require("frontend/react/src/components/KnowledgeRail.jsx", "knowledgeBases", "React knowledge list state")
    require("frontend/react/src/components/KnowledgeRail.jsx", "openMenuKnowledgeBaseId", "React knowledge menu state")
    require("frontend/react/src/components/KnowledgeRail.jsx", "filteredKnowledgeBases", "React knowledge list filter")
    require("frontend/react/src/components/KnowledgeRail.jsx", "knowflow:legacy-knowledge-bases-updated", "React knowledge list receives legacy data")
    require("frontend/react/src/components/KnowledgeRail.jsx", "knowflow:react-open-kb-modal", "React rail knowledge modal open event")
    require("frontend/react/src/components/KnowledgeRail.jsx", "knowflow:react-knowledge-search-change", "React knowledge search event")
    require("frontend/react/src/components/KnowledgeRail.jsx", "knowflow:react-kb-select", "React knowledge select event")
    require("frontend/react/src/components/KnowledgeRail.jsx", "knowflow:react-kb-delete", "React knowledge delete event")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "handleOpenRetrievalDrawer", "React document retrieval handler")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "handleDocumentKnowledgeBaseChange", "React document knowledge base handler")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "handleDocumentSubmit", "React document submit handler")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "handleDocumentFileChange", "React document file change handler")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "handleDocumentDragStart", "React document drag start handler")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "handleDocumentDragEnd", "React document drag end handler")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "handleDocumentDrop", "React document drop handler")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "documents", "React document list owns document state")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "knowledgeBases", "React document upload owns knowledge options")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "selectedKnowledgeBaseId", "React document upload owns selected knowledge base")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "knowflow:legacy-documents-updated", "React document list receives legacy document data")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "knowflow:legacy-knowledge-options-updated", "React document upload receives knowledge options")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "knowflow:legacy-knowledge-selection-updated", "React document upload receives knowledge selection")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "handleDocumentAction", "React document list action handler")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "knowflow:react-open-retrieval-drawer", "React document retrieval event")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "knowflow:react-document-kb-change", "React document knowledge base event")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "knowflow:react-document-submit", "React document submit event")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "knowflow:react-document-file-select", "React document file select event")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "knowflow:react-document-chunks", "React document chunks event")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "knowflow:react-document-reindex", "React document reindex event")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "knowflow:react-document-delete", "React document delete event")
    require("frontend/react/src/components/KnowledgeDocuments.jsx", "knowflow:react-document-remove-pending", "React document remove pending event")
    require("frontend/react/src/components/KnowledgeModals.jsx", "handleKnowledgeModalBackdrop", "React knowledge modal backdrop handler")
    require("frontend/react/src/components/KnowledgeModals.jsx", "handleChunkModalBackdrop", "React chunk modal backdrop handler")
    require("frontend/react/src/components/KnowledgeModals.jsx", "handleKnowledgeBaseSubmit", "React knowledge base submit handler")
    require("frontend/react/src/components/KnowledgeModals.jsx", "knowflow:react-close-kb-modal", "React knowledge modal close event")
    require("frontend/react/src/components/KnowledgeModals.jsx", "knowflow:react-kb-submit", "React knowledge base submit event")
    require("frontend/react/src/components/KnowledgeModals.jsx", "knowflow:react-close-chunk-modal", "React chunk modal close event")
    require("frontend/react/src/components/KnowledgeRetrievalDrawer.jsx", "handleCloseRetrievalDrawer", "React retrieval close handler")
    require("frontend/react/src/components/KnowledgeRetrievalDrawer.jsx", "handleRetrievalSubmit", "React retrieval submit handler")
    require("frontend/react/src/components/KnowledgeRetrievalDrawer.jsx", "knowflow:react-close-retrieval-drawer", "React retrieval close event")
    require("frontend/react/src/components/KnowledgeRetrievalDrawer.jsx", "knowflow:react-retrieval-submit", "React retrieval submit event")
    require("frontend/react/src/components/SettingsPage.jsx", "SettingsHeader", "settings page renders header component")
    require("frontend/react/src/components/SettingsPage.jsx", "ModelConfigForm", "settings page renders model form component")
    require("frontend/react/src/components/SettingsPage.jsx", "ModelListPanel", "settings page renders model list component")
    require("frontend/react/src/components/SettingsPage.jsx", "SettingsSidePanel", "settings page renders side panel component")
    require("frontend/react/src/components/ModelConfigForm.jsx", "model-form", "model form id retained")
    require("frontend/react/src/components/ModelConfigForm.jsx", "model-form-title", "model form title id retained")
    require("frontend/react/src/components/ModelProviderSelector.jsx", "provider-grid", "provider grid id retained")
    require("frontend/react/src/components/ModelConfigForm.jsx", "ModelProviderSelector", "model form renders provider selector")
    require("frontend/react/src/components/ModelProviderSelector.jsx", "provider-card", "provider cards retained")
    require("frontend/react/src/components/ModelProviderSelector.jsx", "useState", "provider selector owns selected provider")
    require("frontend/react/src/components/ModelProviderSelector.jsx", "providerCards.map", "provider selector renders configured cards")
    require("frontend/react/src/components/ModelProviderSelector.jsx", "knowflow:react-provider-change", "React provider bridge event")
    require("frontend/react/src/components/ModelConfigForm.jsx", "model-preset-select", "model preset select id retained")
    require("frontend/react/src/components/ModelConfigForm.jsx", "model-provider", "model provider id retained")
    require("frontend/react/src/components/ModelConfigForm.jsx", "model-submit-btn", "model submit id retained")
    require("frontend/react/src/components/ModelConfigForm.jsx", "model-cancel-btn", "model cancel id retained")
    require("frontend/react/src/components/ModelConfigForm.jsx", "handleModelProviderInput", "React model provider input handler")
    require("frontend/react/src/components/ModelConfigForm.jsx", "handleModelPresetChange", "React model preset handler")
    require("frontend/react/src/components/ModelConfigForm.jsx", "handleModelCancel", "React model cancel handler")
    require("frontend/react/src/components/ModelConfigForm.jsx", "handleModelSubmit", "React model submit handler")
    require("frontend/react/src/components/ModelConfigForm.jsx", "knowflow:react-model-provider-input", "React model provider event")
    require("frontend/react/src/components/ModelConfigForm.jsx", "knowflow:react-model-preset-change", "React model preset event")
    require("frontend/react/src/components/ModelConfigForm.jsx", "knowflow:react-model-cancel", "React model cancel event")
    require("frontend/react/src/components/ModelConfigForm.jsx", "knowflow:react-model-submit", "React model submit event")
    require("frontend/react/src/components/ModelListPanel.jsx", "model-list", "model list id retained")
    require("frontend/react/src/components/ModelListPanel.jsx", "models", "React model list owns model state")
    require("frontend/react/src/components/ModelListPanel.jsx", "knowflow:legacy-models-updated", "React model list receives legacy model data")
    require("frontend/react/src/components/ModelListPanel.jsx", "handleModelAction", "React model list action handler")
    require("frontend/react/src/components/ModelListPanel.jsx", "knowflow:react-model-edit", "React model edit event")
    require("frontend/react/src/components/ModelListPanel.jsx", "knowflow:react-model-test", "React model test event")
    require("frontend/react/src/components/ModelListPanel.jsx", "knowflow:react-model-default", "React model default event")
    require("frontend/react/src/components/ModelListPanel.jsx", "knowflow:react-model-delete", "React model delete event")
    require("frontend/react/src/components/SettingsSidePanel.jsx", "/docs", "settings docs link retained")
    require("frontend/react/src/components/SettingsSidePanel.jsx", "/api/health", "settings health link retained")

    forbid("frontend/react/src/main.jsx", "document.createElement", "legacy script injection in main")
    require("frontend/react/src/App.jsx", "KnowFlowController", "React controller rendered by React")
    require_file("frontend/react/src/components/KnowFlowController.jsx", "KnowFlowController component file")
    require("frontend/react/src/components/KnowFlowController.jsx", "useEffect", "React controller lifecycle")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowReactAuthEnabled", "React auth ownership flag")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowReactAuthStateEnabled", "React auth state ownership flag")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowReactComposerEnabled", "React composer ownership flag")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowReactProviderCardsEnabled", "React provider cards ownership flag")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowReactNavigationEnabled", "React navigation ownership flag")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowReactShellActionsEnabled", "React shell actions ownership flag")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowReactKnowledgeActionsEnabled", "React knowledge actions ownership flag")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowReactUserMenuEnabled", "React user menu ownership flag")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowReactComposerChromeEnabled", "React composer chrome ownership flag")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowReactContextControlsEnabled", "React context controls ownership flag")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowReactSettingsControlsEnabled", "React settings controls ownership flag")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowReactFormActionsEnabled", "React form actions ownership flag")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowReactChatInputEnabled", "React chat input ownership flag")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowReactDocumentUploadEnabled", "React document upload ownership flag")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowReactModelListEnabled", "React model list ownership flag")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowReactDocumentListEnabled", "React document list ownership flag")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowReactKnowledgeDetailEnabled", "React knowledge detail ownership flag")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowReactEvidenceDrawerEnabled", "React evidence drawer ownership flag")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowReactAttachmentTrayEnabled", "React attachment tray ownership flag")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowReactActiveSessionEnabled", "React active session ownership flag")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowReactModelOptionsEnabled", "React model options ownership flag")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowReactKnowledgeOptionsEnabled", "React knowledge options ownership flag")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowReactSendingStateEnabled", "React sending state ownership flag")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowReactToastEnabled", "React toast ownership flag")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowReactSessionListEnabled", "React session list ownership flag")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowReactKnowledgeListEnabled", "React knowledge list ownership flag")
    require("frontend/react/src/controller/knowflowController.js", "__knowflowControllerStarted", "React controller duplicate guard")
    forbid("frontend/react/src/App.jsx", "LegacyControllerBridge", "old legacy bridge import")
    forbid_file("frontend/react/src/components/LegacyControllerBridge.jsx", "old legacy bridge component")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-auth-success", "legacy listens for React auth success")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-auth-logout", "legacy listens for React auth logout")
    require("frontend/react/src/controller/knowflowController.js", "notifyReactAuthStateUpdated", "legacy broadcasts auth state to React")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:legacy-auth-state-updated", "legacy auth state event name")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-toast", "legacy listens for React toast")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-provider-change", "legacy listens for React provider selection")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-page-change", "legacy listens for React page navigation")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-new-chat", "legacy listens for React new chat")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-refresh", "legacy listens for React refresh")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-drawer-toggle", "legacy listens for React drawer toggle")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-drawer-close", "legacy listens for React drawer close")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-sidebar-toggle", "legacy listens for React sidebar toggle")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-history-refresh", "legacy listens for React history refresh")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-composer-menu-toggle", "legacy listens for React composer menu toggle")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-composer-menu-close", "legacy listens for React composer menu close")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-chat-files-change", "legacy listens for React chat files")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-composer-kb-change", "legacy listens for React composer knowledge base")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-chat-model-change", "legacy listens for React chat model")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-chat-kb-change", "legacy listens for React chat knowledge base")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-session-search-change", "legacy listens for React session search")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-open-kb-modal", "legacy listens for React knowledge modal open")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-close-kb-modal", "legacy listens for React knowledge modal close")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-open-retrieval-drawer", "legacy listens for React retrieval drawer open")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-close-retrieval-drawer", "legacy listens for React retrieval drawer close")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-close-chunk-modal", "legacy listens for React chunk modal close")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-knowledge-search-change", "legacy listens for React knowledge search")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-model-provider-input", "legacy listens for React model provider input")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-model-preset-change", "legacy listens for React model preset")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-model-cancel", "legacy listens for React model cancel")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-model-submit", "legacy listens for React model submit")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-kb-submit", "legacy listens for React knowledge base submit")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-document-submit", "legacy listens for React document submit")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-retrieval-submit", "legacy listens for React retrieval submit")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-document-kb-change", "legacy listens for React document knowledge base change")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-chat-submit", "legacy listens for React chat submit")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-chat-input", "legacy listens for React chat input")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-chat-paste", "legacy listens for React chat paste")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-chat-enter-submit", "legacy listens for React chat enter")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-document-file-select", "legacy listens for React document file select")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:legacy-models-updated", "legacy broadcasts model data to React")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-model-edit", "legacy listens for React model edit")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-model-test", "legacy listens for React model test")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-model-default", "legacy listens for React model default")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-model-delete", "legacy listens for React model delete")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:legacy-documents-updated", "legacy broadcasts document data to React")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-document-chunks", "legacy listens for React document chunks")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-document-reindex", "legacy listens for React document reindex")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-document-delete", "legacy listens for React document delete")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-document-remove-pending", "legacy listens for React document remove pending")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:legacy-knowledge-detail-updated", "legacy broadcasts knowledge detail data to React")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:legacy-references-updated", "legacy broadcasts references to React")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:legacy-tool-timeline-updated", "legacy broadcasts tool timeline to React")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:legacy-attachments-updated", "legacy broadcasts attachments to React")
    require("frontend/react/src/controller/knowflowController.js", "notifyReactModelOptionsUpdated", "legacy broadcasts model options to React")
    require("frontend/react/src/controller/knowflowController.js", "notifyReactKnowledgeOptionsUpdated", "legacy broadcasts knowledge options to React")
    require("frontend/react/src/controller/knowflowController.js", "notifyReactModelSelectionUpdated", "legacy broadcasts model selection to React")
    require("frontend/react/src/controller/knowflowController.js", "notifyReactKnowledgeSelectionUpdated", "legacy broadcasts knowledge selection to React")
    require("frontend/react/src/controller/knowflowController.js", "notifyReactSendingUpdated", "legacy broadcasts sending state to React")
    require("frontend/react/src/controller/knowflowController.js", "notifyReactToast", "legacy broadcasts toast state to React")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:legacy-toast", "legacy toast event name")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-attachment-remove", "legacy listens for React attachment remove")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:legacy-active-session-updated", "legacy broadcasts active session to React")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:legacy-sessions-updated", "legacy sends session data to React")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-session-continue", "legacy listens for React session continue")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-session-rename", "legacy listens for React session rename")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-session-delete", "legacy listens for React session delete")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:legacy-knowledge-bases-updated", "legacy sends knowledge base data to React")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-kb-select", "legacy listens for React knowledge select")
    require("frontend/react/src/controller/knowflowController.js", "knowflow:react-kb-delete", "legacy listens for React knowledge delete")
    require("frontend/react/src/controller/knowflowController.js", "if (!window.__knowflowReactAuthEnabled)", "legacy skips auth bindings when React owns auth")
    forbid("frontend/react/src/controller/knowflowController.js", "prompt-chip", "legacy prompt chip binding")
    forbid("frontend/react/src/controller/knowflowController.js", "ReactToolControls", "legacy manual tool ownership")
    forbid("frontend/react/src/controller/knowflowController.js", "react-tool-mode-change", "manual tool mode bridge")
    forbid("frontend/react/src/controller/knowflowController.js", "react-tool-selection-change", "manual tool selection bridge")
    require("frontend/react/src/controller/knowflowController.js", "if (!window.__knowflowReactProviderCardsEnabled)", "legacy skips provider cards when React owns them")
    require("frontend/react/src/controller/knowflowController.js", "if (!window.__knowflowReactNavigationEnabled)", "legacy skips page navigation when React owns it")
    require("frontend/react/src/controller/knowflowController.js", "if (!window.__knowflowReactShellActionsEnabled)", "legacy skips shell actions when React owns them")
    require("frontend/react/src/controller/knowflowController.js", "if (!window.__knowflowReactKnowledgeActionsEnabled)", "legacy skips knowledge actions when React owns them")
    require("frontend/react/src/controller/knowflowController.js", "if (!window.__knowflowReactUserMenuEnabled)", "legacy skips user menu when React owns it")
    require("frontend/react/src/controller/knowflowController.js", "if (!window.__knowflowReactComposerChromeEnabled)", "legacy skips composer chrome when React owns it")
    require("frontend/react/src/controller/knowflowController.js", "if (!window.__knowflowReactContextControlsEnabled)", "legacy skips context controls when React owns them")
    require("frontend/react/src/controller/knowflowController.js", "if (!window.__knowflowReactSettingsControlsEnabled)", "legacy skips settings controls when React owns them")
    require("frontend/react/src/controller/knowflowController.js", "if (!window.__knowflowReactFormActionsEnabled)", "legacy skips form actions when React owns them")
    require("frontend/react/src/controller/knowflowController.js", "if (!window.__knowflowReactChatInputEnabled)", "legacy skips chat input when React owns it")
    require("frontend/react/src/controller/knowflowController.js", "if (!window.__knowflowReactDocumentUploadEnabled)", "legacy skips document upload when React owns it")
    require("frontend/react/src/controller/knowflowController.js", "if (window.__knowflowReactModelListEnabled)", "legacy skips model list rendering when React owns it")
    require("frontend/react/src/controller/knowflowController.js", "if (window.__knowflowReactDocumentListEnabled)", "legacy skips document list rendering when React owns it")
    require("frontend/react/src/controller/knowflowController.js", "if (window.__knowflowReactKnowledgeDetailEnabled)", "legacy skips knowledge detail rendering when React owns it")
    require("frontend/react/src/controller/knowflowController.js", "if (window.__knowflowReactEvidenceDrawerEnabled)", "legacy skips evidence drawer rendering when React owns it")
    require("frontend/react/src/controller/knowflowController.js", "if (window.__knowflowReactAttachmentTrayEnabled)", "legacy skips attachment tray rendering when React owns it")
    require("frontend/react/src/controller/knowflowController.js", "if (window.__knowflowReactActiveSessionEnabled)", "legacy skips active session rendering when React owns it")
    require("frontend/react/src/controller/knowflowController.js", "if (window.__knowflowReactSessionListEnabled)", "legacy skips session rendering when React owns it")
    require("frontend/react/src/controller/knowflowController.js", "if (window.__knowflowReactKnowledgeListEnabled)", "legacy skips knowledge rendering when React owns it")

    forbid_file("frontend/react/src/legacyTemplate.js", "legacy template after React component extraction")
    require("frontend/react/src/controller/knowflowController.js", "bootstrap", "legacy controller bridge")

    readme = read("README.md")
    for token in ["闁?", "缂?", "閻?", "濞戞挴鍋?"]:
        if token in readme:
            raise AssertionError(f"README still contains mojibake token: {token}")


if __name__ == "__main__":
    main()


